//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Company {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Company() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedinetClassLibrary.Resources.Models.Company", typeof(Company).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address field must be a string with a maximum length of 500..
        /// </summary>
        public static string AddressLength {
            get {
                return ResourceManager.GetString("AddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address field is required..
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated company.
        /// </summary>
        public static string AssociatedCompany {
            get {
                return ResourceManager.GetString("AssociatedCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company sector.
        /// </summary>
        public static string CompanySector {
            get {
                return ResourceManager.GetString("CompanySector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company sector field is required..
        /// </summary>
        public static string CompanySectorRequired {
            get {
                return ResourceManager.GetString("CompanySectorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company type.
        /// </summary>
        public static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company type field is required..
        /// </summary>
        public static string CompanyTypeRequired {
            get {
                return ResourceManager.GetString("CompanyTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact field must be a string with a maximum length of 50..
        /// </summary>
        public static string ContactLength {
            get {
                return ResourceManager.GetString("ContactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact field is required..
        /// </summary>
        public static string ContactRequired {
            get {
                return ResourceManager.GetString("ContactRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number field must be a string with a maximum length of 20..
        /// </summary>
        public static string NumberLength {
            get {
                return ResourceManager.GetString("NumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number field is required..
        /// </summary>
        public static string NumberRequired {
            get {
                return ResourceManager.GetString("NumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone field is invalid..
        /// </summary>
        public static string PhoneInvalid {
            get {
                return ResourceManager.GetString("PhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone field must be a string with a maximum length of 20..
        /// </summary>
        public static string PhoneLength {
            get {
                return ResourceManager.GetString("PhoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone field is required..
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show climate?.
        /// </summary>
        public static string ShowClimate {
            get {
                return ResourceManager.GetString("ShowClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Show climate field is required..
        /// </summary>
        public static string ShowClimateRequired {
            get {
                return ResourceManager.GetString("ShowClimateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Url field is invalid..
        /// </summary>
        public static string UrlInvalid {
            get {
                return ResourceManager.GetString("UrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Url field must be a string with a maximum length of 100..
        /// </summary>
        public static string UrlLength {
            get {
                return ResourceManager.GetString("UrlLength", resourceCulture);
            }
        }
    }
}
