//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Test {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Test() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedinetClassLibrary.Resources.Models.Test", typeof(Test).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate scale.
        /// </summary>
        public static string ClimateScale {
            get {
                return ResourceManager.GetString("ClimateScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Climate scale field is required..
        /// </summary>
        public static string ClimateScaleRequired {
            get {
                return ResourceManager.GetString("ClimateScaleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence level.
        /// </summary>
        public static string ConfidenceLevel {
            get {
                return ResourceManager.GetString("ConfidenceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disordered questions.
        /// </summary>
        public static string Disordered {
            get {
                return ResourceManager.GetString("Disordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Disordered questions field is required..
        /// </summary>
        public static string DisorderedRequired {
            get {
                return ResourceManager.GetString("DisorderedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The End date field is required..
        /// </summary>
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation number.
        /// </summary>
        public static string EvaluationNumber {
            get {
                return ResourceManager.GetString("EvaluationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Evaluation number field must be a whole number greater than zero..
        /// </summary>
        public static string EvaluationNumberInvalid {
            get {
                return ResourceManager.GetString("EvaluationNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Evaluation number field is required..
        /// </summary>
        public static string EvaluationNumberRequired {
            get {
                return ResourceManager.GetString("EvaluationNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by categories.
        /// </summary>
        public static string GroupByCategories {
            get {
                return ResourceManager.GetString("GroupByCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Group by categories field is required..
        /// </summary>
        public static string GroupByCategoriesRequired {
            get {
                return ResourceManager.GetString("GroupByCategoriesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum people.
        /// </summary>
        public static string MinimumPeople {
            get {
                return ResourceManager.GetString("MinimumPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Minimum people field must be a whole number greater than 0..
        /// </summary>
        public static string MinimumPeopleInvalid {
            get {
                return ResourceManager.GetString("MinimumPeopleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Minimum people field is required..
        /// </summary>
        public static string MinimumPeopleRequired {
            get {
                return ResourceManager.GetString("MinimumPeopleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of employees.
        /// </summary>
        public static string NumberOfEmployees {
            get {
                return ResourceManager.GetString("NumberOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One questionnaire.
        /// </summary>
        public static string OneQuestionnaire {
            get {
                return ResourceManager.GetString("OneQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The One questionnaire field is required..
        /// </summary>
        public static string OneQuestionnaireRequired {
            get {
                return ResourceManager.GetString("OneQuestionnaireRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous test.
        /// </summary>
        public static string PreviousTest {
            get {
                return ResourceManager.GetString("PreviousTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        public static string Questionnaire {
            get {
                return ResourceManager.GetString("Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Questionnaire field is required..
        /// </summary>
        public static string QuestionnaireRequired {
            get {
                return ResourceManager.GetString("QuestionnaireRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaires.
        /// </summary>
        public static string Questionnaires {
            get {
                return ResourceManager.GetString("Questionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records per page.
        /// </summary>
        public static string RecordsPerPage {
            get {
                return ResourceManager.GetString("RecordsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Records per page field must be a whole number greater than 0..
        /// </summary>
        public static string RecordsPerPageInvalid {
            get {
                return ResourceManager.GetString("RecordsPerPageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Records per page field is required..
        /// </summary>
        public static string RecordsPerPageRequired {
            get {
                return ResourceManager.GetString("RecordsPerPageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result based on 100.
        /// </summary>
        public static string ResultBasedOn100 {
            get {
                return ResourceManager.GetString("ResultBasedOn100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Result based on 100 field is required..
        /// </summary>
        public static string ResultBasedOn100Required {
            get {
                return ResourceManager.GetString("ResultBasedOn100Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard error.
        /// </summary>
        public static string StandardError {
            get {
                return ResourceManager.GetString("StandardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Start date field is required..
        /// </summary>
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Text field is required..
        /// </summary>
        public static string TextRequired {
            get {
                return ResourceManager.GetString("TextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted categories.
        /// </summary>
        public static string Weighted {
            get {
                return ResourceManager.GetString("Weighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Weighted categories field is required..
        /// </summary>
        public static string WeightedRequired {
            get {
                return ResourceManager.GetString("WeightedRequired", resourceCulture);
            }
        }
    }
}
