//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Views.ChartReport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Graphics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Graphics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedinetClassLibrary.Resources.Views.ChartReport.Graphics", typeof(Graphics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  obteined .
        /// </summary>
        public static string Acquired {
            get {
                return ResourceManager.GetString("Acquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age ranges..
        /// </summary>
        public static string AgeRanges {
            get {
                return ResourceManager.GetString("AgeRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age range results.
        /// </summary>
        public static string AgeRangesTitle {
            get {
                return ResourceManager.GetString("AgeRangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age ranges.
        /// </summary>
        public static string AgeTab {
            get {
                return ResourceManager.GetString("AgeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tests.
        /// </summary>
        public static string AllTests {
            get {
                return ResourceManager.GetString("AllTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociation analysis/ correlation/ significative difference..
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and result.
        /// </summary>
        public static string AndResult {
            get {
                return ResourceManager.GetString("AndResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  areas..
        /// </summary>
        public static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis X: .
        /// </summary>
        public static string AxisX {
            get {
                return ResourceManager.GetString("AxisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Y: .
        /// </summary>
        public static string AxisY {
            get {
                return ResourceManager.GetString("AxisY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the demographics.
        /// </summary>
        public static string BivariateSelect {
            get {
                return ResourceManager.GetString("BivariateSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual graphics.
        /// </summary>
        public static string BivariateTitle {
            get {
                return ResourceManager.GetString("BivariateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to branches..
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch results.
        /// </summary>
        public static string BranchesTitle {
            get {
                return ResourceManager.GetString("BranchesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By category.
        /// </summary>
        public static string ByCategory {
            get {
                return ResourceManager.GetString("ByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By question.
        /// </summary>
        public static string ByQuestion {
            get {
                return ResourceManager.GetString("ByQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: .
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoryTab {
            get {
                return ResourceManager.GetString("CategoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category graphics.
        /// </summary>
        public static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical chi-square.
        /// </summary>
        public static string ChiSquareValue {
            get {
                return ResourceManager.GetString("ChiSquareValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the section:.
        /// </summary>
        public static string ChooseSection {
            get {
                return ResourceManager.GetString("ChooseSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate.
        /// </summary>
        public static string Climate {
            get {
                return ResourceManager.GetString("Climate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate ranges.
        /// </summary>
        public static string ClimateRangeTab {
            get {
                return ResourceManager.GetString("ClimateRangeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate scales.
        /// </summary>
        public static string ClimateScaleTab {
            get {
                return ResourceManager.GetString("ClimateScaleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  state, .
        /// </summary>
        public static string ColorState {
            get {
                return ResourceManager.GetString("ColorState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments: .
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  companies..
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string CompanyTab {
            get {
                return ResourceManager.GetString("CompanyTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative by category.
        /// </summary>
        public static string ComparativeByCategory {
            get {
                return ResourceManager.GetString("ComparativeByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative by question.
        /// </summary>
        public static string ComparativeByQuestion {
            get {
                return ResourceManager.GetString("ComparativeByQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative graphics.
        /// </summary>
        public static string ComparativeTitle {
            get {
                return ResourceManager.GetString("ComparativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with:.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conclusion.
        /// </summary>
        public static string Conclusion {
            get {
                return ResourceManager.GetString("Conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validez de la muestra en términos estadísticos. Señala la probabilidad de que el parámetro poblacional se encuentre dentro del intervalo de confianza a generar..
        /// </summary>
        public static string ConfidenceTip {
            get {
                return ResourceManager.GetString("ConfidenceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to corresponding to a .
        /// </summary>
        public static string Corresponding {
            get {
                return ResourceManager.GetString("Corresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string CountryTab {
            get {
                return ResourceManager.GetString("CountryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demographics.
        /// </summary>
        public static string Demographics {
            get {
                return ResourceManager.GetString("Demographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select different demographic.
        /// </summary>
        public static string DemographicsEquals {
            get {
                return ResourceManager.GetString("DemographicsEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptive analysis.
        /// </summary>
        public static string DescriptiveAnalysis {
            get {
                return ResourceManager.GetString("DescriptiveAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        public static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  dimensions..
        /// </summary>
        public static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension results.
        /// </summary>
        public static string DimensionsTitle {
            get {
                return ResourceManager.GetString("DimensionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download chart.
        /// </summary>
        public static string DownloadImage {
            get {
                return ResourceManager.GetString("DownloadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit results.
        /// </summary>
        public static string EditResultsTitle {
            get {
                return ResourceManager.GetString("EditResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of employees used for measurement: .
        /// </summary>
        public static string EmployeesUsed {
            get {
                return ResourceManager.GetString("EmployeesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of employees who performed the measurements: .
        /// </summary>
        public static string EmployeesWhoPerformed {
            get {
                return ResourceManager.GetString("EmployeesWhoPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum difference between the statistic and the population parameter, usually an error greater than 6% is considered, in most cases, as a high level error..
        /// </summary>
        public static string ErrorTip {
            get {
                return ResourceManager.GetString("ErrorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive report.
        /// </summary>
        public static string ExecutiveReport {
            get {
                return ResourceManager.GetString("ExecutiveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive report.
        /// </summary>
        public static string ExecutiveReportTitle {
            get {
                return ResourceManager.GetString("ExecutiveReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External ranking.
        /// </summary>
        public static string ExternalRanking {
            get {
                return ResourceManager.GetString("ExternalRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string FeatureTab {
            get {
                return ResourceManager.GetString("FeatureTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedbacks.
        /// </summary>
        public static string FeedbackTab {
            get {
                return ResourceManager.GetString("FeedbackTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional structures.
        /// </summary>
        public static string FOrganizationTab {
            get {
                return ResourceManager.GetString("FOrganizationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional organization type results.
        /// </summary>
        public static string FOTypesTitle {
            get {
                return ResourceManager.GetString("FOTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional structure types.
        /// </summary>
        public static string FOTypeTab {
            get {
                return ResourceManager.GetString("FOTypeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency graphics.
        /// </summary>
        public static string FrequencyTitle {
            get {
                return ResourceManager.GetString("FrequencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  location from a number of .
        /// </summary>
        public static string FromANumber {
            get {
                return ResourceManager.GetString("FromANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functionally, the best results resulted in the .
        /// </summary>
        public static string FunctionallyHighest {
            get {
                return ResourceManager.GetString("FunctionallyHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  areas; whereas, the lowest results correspond to the .
        /// </summary>
        public static string FunctionallyLowest {
            get {
                return ResourceManager.GetString("FunctionallyLowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genders.
        /// </summary>
        public static string GenderTab {
            get {
                return ResourceManager.GetString("GenderTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Answers.
        /// </summary>
        public static string GeneralAnswers {
            get {
                return ResourceManager.GetString("GeneralAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Average.
        /// </summary>
        public static string GeneralAverage {
            get {
                return ResourceManager.GetString("GeneralAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Categories.
        /// </summary>
        public static string GeneralCategory {
            get {
                return ResourceManager.GetString("GeneralCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Result.
        /// </summary>
        public static string GeneralClimate {
            get {
                return ResourceManager.GetString("GeneralClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Frequency.
        /// </summary>
        public static string GeneralFrequency {
            get {
                return ResourceManager.GetString("GeneralFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General result for measurement .
        /// </summary>
        public static string GeneralResult {
            get {
                return ResourceManager.GetString("GeneralResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Sample.
        /// </summary>
        public static string GeneralSample {
            get {
                return ResourceManager.GetString("GeneralSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to determine the most significant differences in variables, hrmedinet performed an analysis between climate and said variables. Following are the results:.
        /// </summary>
        public static string HRMedinetPerformed {
            get {
                return ResourceManager.GetString("HRMedinetPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrmedinet performed a multivariable analysis in order to determine the variables affecting variation of climate level. The results, which involve 95% of the variations, are as follows:.
        /// </summary>
        public static string HRPerformedMultivariable {
            get {
                return ResourceManager.GetString("HRPerformedMultivariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  in .
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction levels.
        /// </summary>
        public static string InstructionLevelTab {
            get {
                return ResourceManager.GetString("InstructionLevelTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal ranking.
        /// </summary>
        public static string InternalRanking {
            get {
                return ResourceManager.GetString("InternalRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is placed at number .
        /// </summary>
        public static string IsPlaced {
            get {
                return ResourceManager.GetString("IsPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string LocationTab {
            get {
                return ResourceManager.GetString("LocationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string Median {
            get {
                return ResourceManager.GetString("Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My company.
        /// </summary>
        public static string MyCompany {
            get {
                return ResourceManager.GetString("MyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of negative feedback.
        /// </summary>
        public static string NegativePercentage {
            get {
                return ResourceManager.GetString("NegativePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of neutral feedback.
        /// </summary>
        public static string NeutralPercentage {
            get {
                return ResourceManager.GetString("NeutralPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No evaluations available at this time to view reports of the test .
        /// </summary>
        public static string NoEvaluationsText {
            get {
                return ResourceManager.GetString("NoEvaluationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        public static string NoEvaluationsTitle {
            get {
                return ResourceManager.GetString("NoEvaluationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available results yet due to lack of minimum-required evaluations set by your company..
        /// </summary>
        public static string NoMinimumRequired {
            get {
                return ResourceManager.GetString("NoMinimumRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- None --.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-satisfied.
        /// </summary>
        public static string NoSatisfied {
            get {
                return ResourceManager.GetString("NoSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Received.
        /// </summary>
        public static string NotReceived {
            get {
                return ResourceManager.GetString("NotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No variables with significant association were found..
        /// </summary>
        public static string NoVariables {
            get {
                return ResourceManager.GetString("NoVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../Content/Images/icon-system/OneDemographic.png.
        /// </summary>
        public static string OneDemographicImage {
            get {
                return ResourceManager.GetString("OneDemographicImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionTab {
            get {
                return ResourceManager.GetString("OptionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our chi-square value.
        /// </summary>
        public static string OurChiSquare {
            get {
                return ResourceManager.GetString("OurChiSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parametres {
            get {
                return ResourceManager.GetString("Parametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of received evaluations: .
        /// </summary>
        public static string PercentageEvaluationReceived {
            get {
                return ResourceManager.GetString("PercentageEvaluationReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance evaluations.
        /// </summary>
        public static string PerformanceTab {
            get {
                return ResourceManager.GetString("PerformanceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period: .
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        public static string Periods {
            get {
                return ResourceManager.GetString("Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population.
        /// </summary>
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # people.
        /// </summary>
        public static string PopulationNroPeople {
            get {
                return ResourceManager.GetString("PopulationNroPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % people.
        /// </summary>
        public static string PopulationPctPeople {
            get {
                return ResourceManager.GetString("PopulationPctPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population graphics.
        /// </summary>
        public static string PopulationTitle {
            get {
                return ResourceManager.GetString("PopulationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position levels.
        /// </summary>
        public static string PositionLevelTab {
            get {
                return ResourceManager.GetString("PositionLevelTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive feedback per category.
        /// </summary>
        public static string PositiveByCategory {
            get {
                return ResourceManager.GetString("PositiveByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive feedback per question.
        /// </summary>
        public static string PositiveByQuestion {
            get {
                return ResourceManager.GetString("PositiveByQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of positive market feedback.
        /// </summary>
        public static string PositiveMarket {
            get {
                return ResourceManager.GetString("PositiveMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of positive feedback.
        /// </summary>
        public static string PositivePercentage {
            get {
                return ResourceManager.GetString("PositivePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print graphics.
        /// </summary>
        public static string PrintGraphics {
            get {
                return ResourceManager.GetString("PrintGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population graphics.
        /// </summary>
        public static string PrintPopulation {
            get {
                return ResourceManager.GetString("PrintPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print ranking.
        /// </summary>
        public static string PrintRanking {
            get {
                return ResourceManager.GetString("PrintRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print report.
        /// </summary>
        public static string PrintReport {
            get {
                return ResourceManager.GetString("PrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print results.
        /// </summary>
        public static string PrintResults {
            get {
                return ResourceManager.GetString("PrintResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print this section.
        /// </summary>
        public static string PrintSection {
            get {
                return ResourceManager.GetString("PrintSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of this report is to summarize general aspects of organizational climate for the country/region/department among others..
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PValue:.
        /// </summary>
        public static string PValue {
            get {
                return ResourceManager.GetString("PValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions: .
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        public static string Questionnaire {
            get {
                return ResourceManager.GetString("Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaires.
        /// </summary>
        public static string QuestionnaireTab {
            get {
                return ResourceManager.GetString("QuestionnaireTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string QuestionTab {
            get {
                return ResourceManager.GetString("QuestionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string RegionTab {
            get {
                return ResourceManager.GetString("RegionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registering a percentage of favorable-results of employees of .
        /// </summary>
        public static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  result..
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample received.
        /// </summary>
        public static string SampleReceived {
            get {
                return ResourceManager.GetString("SampleReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfaction tables.
        /// </summary>
        public static string SatisfactionTitle {
            get {
                return ResourceManager.GetString("SatisfactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfied.
        /// </summary>
        public static string Satisfied {
            get {
                return ResourceManager.GetString("Satisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a demographic to see results..
        /// </summary>
        public static string SelectDemographic {
            get {
                return ResourceManager.GetString("SelectDemographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a question to see results..
        /// </summary>
        public static string SelectQuestion {
            get {
                return ResourceManager.GetString("SelectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a questionnaire and a company sector..
        /// </summary>
        public static string SelectQuestionnaireAndSector {
            get {
                return ResourceManager.GetString("SelectQuestionnaireAndSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seniority ranges.
        /// </summary>
        public static string SeniorityTab {
            get {
                return ResourceManager.GetString("SeniorityTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significance level: .
        /// </summary>
        public static string SignificanceLevel {
            get {
                return ResourceManager.GetString("SignificanceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refers to the maximum probability required to reject a null hypothesis. Null hypothesis or of no relation between variables. By default, a significance level of 0.05 is considered to be a &apos;medium&apos; level..
        /// </summary>
        public static string SignificanceTip {
            get {
                return ResourceManager.GetString("SignificanceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States of .
        /// </summary>
        public static string StateTab {
            get {
                return ResourceManager.GetString("StateTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical reports.
        /// </summary>
        public static string StatisticalReports {
            get {
                return ResourceManager.GetString("StatisticalReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At a strata level, the results show that employees of job positions .
        /// </summary>
        public static string StrataLevel {
            get {
                return ResourceManager.GetString("StrataLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of positive feedback; whereas, employees of other job positions obtained  .
        /// </summary>
        public static string StrataLevelEmployees {
            get {
                return ResourceManager.GetString("StrataLevelEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: .
        /// </summary>
        public static string TableTitle {
            get {
                return ResourceManager.GetString("TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: .
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string TestTab {
            get {
                return ResourceManager.GetString("TestTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Answers.
        /// </summary>
        public static string TextAnswersTitle {
            get {
                return ResourceManager.GetString("TextAnswersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comparative results show that from a selected sample of companies to compare by client. .
        /// </summary>
        public static string TheComparativeRanking {
            get {
                return ResourceManager.GetString("TheComparativeRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The general results indicate that the climate level of your company is .
        /// </summary>
        public static string TheGeneralResultsIndicate {
            get {
                return ResourceManager.GetString("TheGeneralResultsIndicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highest results are shown in .
        /// </summary>
        public static string TheHighestAgeRangeResults {
            get {
                return ResourceManager.GetString("TheHighestAgeRangeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highest results are shown in .
        /// </summary>
        public static string TheHighestBranchResults {
            get {
                return ResourceManager.GetString("TheHighestBranchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highest results are shown in .
        /// </summary>
        public static string TheHighestCategoryResults {
            get {
                return ResourceManager.GetString("TheHighestCategoryResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highest results are shown in .
        /// </summary>
        public static string TheHighestFOTypeResults {
            get {
                return ResourceManager.GetString("TheHighestFOTypeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  age ranges, whereas the lowest results are shown in .
        /// </summary>
        public static string TheLowestAgeRangeResults {
            get {
                return ResourceManager.GetString("TheLowestAgeRangeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  branches, whereas the lowest results are shown in .
        /// </summary>
        public static string TheLowestBranchResults {
            get {
                return ResourceManager.GetString("TheLowestBranchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  dimensions, whereas the lowest results are shown in .
        /// </summary>
        public static string TheLowestCategoryResults {
            get {
                return ResourceManager.GetString("TheLowestCategoryResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , whereas the lowest results are shown in .
        /// </summary>
        public static string TheLowestFOTypeResults {
            get {
                return ResourceManager.GetString("TheLowestFOTypeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Univariate graphics.
        /// </summary>
        public static string UnivariateTitle {
            get {
                return ResourceManager.GetString("UnivariateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserTab {
            get {
                return ResourceManager.GetString("UserTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables with significant association: .
        /// </summary>
        public static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables affecting climate level..
        /// </summary>
        public static string VariablesAffecting {
            get {
                return ResourceManager.GetString("VariablesAffecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
