//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Views.ChartReport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ranking {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ranking() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedinetClassLibrary.Resources.Views.ChartReport.Ranking", typeof(Ranking).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By country.
        /// </summary>
        public static string ByCountry {
            get {
                return ResourceManager.GetString("ByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. There are no companies in selected items..
        /// </summary>
        public static string NoCompanies {
            get {
                return ResourceManager.GetString("NoCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. There has been no measurement with the selected questionnaire..
        /// </summary>
        public static string NoDemographics {
            get {
                return ResourceManager.GetString("NoDemographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print external ranking.
        /// </summary>
        public static string PrintExternalRanking {
            get {
                return ResourceManager.GetString("PrintExternalRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print internal ranking.
        /// </summary>
        public static string PrintInternalRanking {
            get {
                return ResourceManager.GetString("PrintInternalRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print ranking.
        /// </summary>
        public static string PrintRankingTitle {
            get {
                return ResourceManager.GetString("PrintRankingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print this ranking.
        /// </summary>
        public static string PrintThisRanking {
            get {
                return ResourceManager.GetString("PrintThisRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string RankingTitle {
            get {
                return ResourceManager.GetString("RankingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a company to see demographics..
        /// </summary>
        public static string SelectCompany {
            get {
                return ResourceManager.GetString("SelectCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a company to print results..
        /// </summary>
        public static string SelectCompanyPrint {
            get {
                return ResourceManager.GetString("SelectCompanyPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a country to see results..
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a sector to see results..
        /// </summary>
        public static string SelectSector {
            get {
                return ResourceManager.GetString("SelectSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a sector and a country to see results..
        /// </summary>
        public static string SelectSectorAndCountry {
            get {
                return ResourceManager.GetString("SelectSectorAndCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a sector and a country to print results..
        /// </summary>
        public static string SelectSectorAndCountryPrint {
            get {
                return ResourceManager.GetString("SelectSectorAndCountryPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a sector to print results..
        /// </summary>
        public static string SelectSectorPrint {
            get {
                return ResourceManager.GetString("SelectSectorPrint", resourceCulture);
            }
        }
    }
}
