//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Views.ChartReport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportsList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportsList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedinetClassLibrary.Resources.Views.ChartReport.ReportsList", typeof(ReportsList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnswerImage {
            get {
                return ResourceManager.GetString("AnswerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Report list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bivariate reports.
        /// </summary>
        public static string Bivariate {
            get {
                return ResourceManager.GetString("Bivariate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bivariate-en.
        /// </summary>
        public static string BivariateImage {
            get {
                return ResourceManager.GetString("BivariateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category reports.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category-en.
        /// </summary>
        public static string CategoryImage {
            get {
                return ResourceManager.GetString("CategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative.
        /// </summary>
        public static string Comparative {
            get {
                return ResourceManager.GetString("Comparative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comparative-es.
        /// </summary>
        public static string ComparativeImage {
            get {
                return ResourceManager.GetString("ComparativeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedbacks-en.
        /// </summary>
        public static string FeedbacksImage {
            get {
                return ResourceManager.GetString("FeedbacksImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency reports.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frequency-en.
        /// </summary>
        public static string FrequencyImage {
            get {
                return ResourceManager.GetString("FrequencyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDemographic-en.
        /// </summary>
        public static string OneDemographicImage {
            get {
                return ResourceManager.GetString("OneDemographicImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population reports.
        /// </summary>
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to population-en.
        /// </summary>
        public static string PopulationImage {
            get {
                return ResourceManager.GetString("PopulationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ranking-en.
        /// </summary>
        public static string RankingImage {
            get {
                return ResourceManager.GetString("RankingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic reports.
        /// </summary>
        public static string Regression {
            get {
                return ResourceManager.GetString("Regression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regression-en.
        /// </summary>
        public static string RegressionImage {
            get {
                return ResourceManager.GetString("RegressionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive reports.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report-en.
        /// </summary>
        public static string ResultImage {
            get {
                return ResourceManager.GetString("ResultImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfaction table.
        /// </summary>
        public static string Satisfaction {
            get {
                return ResourceManager.GetString("Satisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to satisfaction-es.
        /// </summary>
        public static string SatisfactionImage {
            get {
                return ResourceManager.GetString("SatisfactionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text answers.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-en.
        /// </summary>
        public static string TextImage {
            get {
                return ResourceManager.GetString("TextImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Univariate reports.
        /// </summary>
        public static string Univariate {
            get {
                return ResourceManager.GetString("Univariate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to univariate-en.
        /// </summary>
        public static string UnivariateImage {
            get {
                return ResourceManager.GetString("UnivariateImage", resourceCulture);
            }
        }
    }
}
