//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChartReports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChartReports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedinetClassLibrary.Resources.Controllers.ChartReports", typeof(ChartReports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: Results by age range.
        /// </summary>
        public static string AgeCategory {
            get {
                return ResourceManager.GetString("AgeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by age range.
        /// </summary>
        public static string AgeClimate {
            get {
                return ResourceManager.GetString("AgeClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency: Results by age range.
        /// </summary>
        public static string AgeFrequency {
            get {
                return ResourceManager.GetString("AgeFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of evaluations by age range.
        /// </summary>
        public static string AgePercentage {
            get {
                return ResourceManager.GetString("AgePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: Results by .
        /// </summary>
        public static string CategoryBy {
            get {
                return ResourceManager.GetString("CategoryBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by category.
        /// </summary>
        public static string CategoryClimate {
            get {
                return ResourceManager.GetString("CategoryClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by .
        /// </summary>
        public static string ClimateBy {
            get {
                return ResourceManager.GetString("ClimateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative: Result by .
        /// </summary>
        public static string ClimateComparative {
            get {
                return ResourceManager.GetString("ClimateComparative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: Results by country.
        /// </summary>
        public static string CountryCategory {
            get {
                return ResourceManager.GetString("CountryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by country.
        /// </summary>
        public static string CountryClimate {
            get {
                return ResourceManager.GetString("CountryClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency: Results by country.
        /// </summary>
        public static string CountryFrequency {
            get {
                return ResourceManager.GetString("CountryFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of evaluations by country.
        /// </summary>
        public static string CountryPercentage {
            get {
                return ResourceManager.GetString("CountryPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency: Results by .
        /// </summary>
        public static string FrequencyBy {
            get {
                return ResourceManager.GetString("FrequencyBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: Results by gender.
        /// </summary>
        public static string GenderCategory {
            get {
                return ResourceManager.GetString("GenderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by gender.
        /// </summary>
        public static string GenderClimate {
            get {
                return ResourceManager.GetString("GenderClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency: Results by gender.
        /// </summary>
        public static string GenderFrequency {
            get {
                return ResourceManager.GetString("GenderFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of evaluations by gender.
        /// </summary>
        public static string GenderPercentage {
            get {
                return ResourceManager.GetString("GenderPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: General results.
        /// </summary>
        public static string GeneralCategory {
            get {
                return ResourceManager.GetString("GeneralCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General results.
        /// </summary>
        public static string GeneralClimate {
            get {
                return ResourceManager.GetString("GeneralClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency: General results.
        /// </summary>
        public static string GeneralFrequency {
            get {
                return ResourceManager.GetString("GeneralFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: Results by instruction level.
        /// </summary>
        public static string InstructionLevelCategory {
            get {
                return ResourceManager.GetString("InstructionLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by instruction level.
        /// </summary>
        public static string InstructionLevelClimate {
            get {
                return ResourceManager.GetString("InstructionLevelClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency: Results by instruction level.
        /// </summary>
        public static string InstructionLevelFrequency {
            get {
                return ResourceManager.GetString("InstructionLevelFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of evaluations by instruction level.
        /// </summary>
        public static string InstructionLevelPercentage {
            get {
                return ResourceManager.GetString("InstructionLevelPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: Results by branch.
        /// </summary>
        public static string LocationCategory {
            get {
                return ResourceManager.GetString("LocationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by branch.
        /// </summary>
        public static string LocationClimate {
            get {
                return ResourceManager.GetString("LocationClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency: Results by branch.
        /// </summary>
        public static string LocationFrequency {
            get {
                return ResourceManager.GetString("LocationFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of evaluations by branch.
        /// </summary>
        public static string LocationPercentage {
            get {
                return ResourceManager.GetString("LocationPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement history.
        /// </summary>
        public static string MeasurementHistory {
            get {
                return ResourceManager.GetString("MeasurementHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string Median {
            get {
                return ResourceManager.GetString("Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not received.
        /// </summary>
        public static string NotReceived {
            get {
                return ResourceManager.GetString("NotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of evaluations by.
        /// </summary>
        public static string PercentageBy {
            get {
                return ResourceManager.GetString("PercentageBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: Results by performance evaluation.
        /// </summary>
        public static string PerformanceCategory {
            get {
                return ResourceManager.GetString("PerformanceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by performance evaluation.
        /// </summary>
        public static string PerformanceClimate {
            get {
                return ResourceManager.GetString("PerformanceClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency: Results by performance evaluation.
        /// </summary>
        public static string PerformanceFrequency {
            get {
                return ResourceManager.GetString("PerformanceFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of evaluations by performance evaluation.
        /// </summary>
        public static string PerformancePercentage {
            get {
                return ResourceManager.GetString("PerformancePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative: Population.
        /// </summary>
        public static string PopulationComparative {
            get {
                return ResourceManager.GetString("PopulationComparative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: Results by position level.
        /// </summary>
        public static string PositionLevelCategory {
            get {
                return ResourceManager.GetString("PositionLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by position level.
        /// </summary>
        public static string PositionLevelClimate {
            get {
                return ResourceManager.GetString("PositionLevelClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Results by position level.
        /// </summary>
        public static string PositionLevelFrequency {
            get {
                return ResourceManager.GetString("PositionLevelFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of evaluations by position level.
        /// </summary>
        public static string PositionLevelPercentage {
            get {
                return ResourceManager.GetString("PositionLevelPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: Results by region.
        /// </summary>
        public static string RegionCategory {
            get {
                return ResourceManager.GetString("RegionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by region.
        /// </summary>
        public static string RegionClimate {
            get {
                return ResourceManager.GetString("RegionClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency: Results by region.
        /// </summary>
        public static string RegionFrequency {
            get {
                return ResourceManager.GetString("RegionFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of evaluations by region.
        /// </summary>
        public static string RegionPercentage {
            get {
                return ResourceManager.GetString("RegionPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: Results by seniority range.
        /// </summary>
        public static string SeniorityCategory {
            get {
                return ResourceManager.GetString("SeniorityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by seniority range.
        /// </summary>
        public static string SeniorityClimate {
            get {
                return ResourceManager.GetString("SeniorityClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency: Results by seniority range.
        /// </summary>
        public static string SeniorityFrequency {
            get {
                return ResourceManager.GetString("SeniorityFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of evaluations by seniority range.
        /// </summary>
        public static string SeniorityPercentage {
            get {
                return ResourceManager.GetString("SeniorityPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: Results by state of .
        /// </summary>
        public static string StateCategory {
            get {
                return ResourceManager.GetString("StateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by state of .
        /// </summary>
        public static string StateClimate {
            get {
                return ResourceManager.GetString("StateClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency: Results by state of .
        /// </summary>
        public static string StateFrequency {
            get {
                return ResourceManager.GetString("StateFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of evaluations by states of .
        /// </summary>
        public static string StatePercentage {
            get {
                return ResourceManager.GetString("StatePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total evaluations: .
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
