//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Controllers {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tests() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedinetClassLibrary.Resources.Controllers.Tests", typeof(Tests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code not found..
        /// </summary>
        public static string CodeNotFound {
            get {
                return ResourceManager.GetString("CodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a valid evaluation code..
        /// </summary>
        public static string CodeNotFoundText {
            get {
                return ResourceManager.GetString("CodeNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code doesn&apos;t exist..
        /// </summary>
        public static string CodeText {
            get {
                return ResourceManager.GetString("CodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Created with success.
        /// </summary>
        public static string Createdwithsuccess {
            get {
                return ResourceManager.GetString("Createdwithsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The measurement has been successfully created.
        /// </summary>
        public static string CreatedwithsuccessText {
            get {
                return ResourceManager.GetString("CreatedwithsuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demographic required.
        /// </summary>
        public static string Demograph {
            get {
                return ResourceManager.GetString("Demograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demographic measure can not be null..
        /// </summary>
        public static string DemographicsText {
            get {
                return ResourceManager.GetString("DemographicsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End date must be after the Start time..
        /// </summary>
        public static string EndDateTestText {
            get {
                return ResourceManager.GetString("EndDateTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The test you are trying to access is closed..
        /// </summary>
        public static string EndDateText {
            get {
                return ResourceManager.GetString("EndDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluation number.
        /// </summary>
        public static string EvaluationNumber {
            get {
                return ResourceManager.GetString("EvaluationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The test you are trying to access has been completed..
        /// </summary>
        public static string EvaluationNumberText {
            get {
                return ResourceManager.GetString("EvaluationNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IP duplicated.
        /// </summary>
        public static string IPDuplicated {
            get {
                return ResourceManager.GetString("IPDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The IP from which you are trying to carry out the measurement has already been used..
        /// </summary>
        public static string IPDuplicatedText {
            get {
                return ResourceManager.GetString("IPDuplicatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum people.
        /// </summary>
        public static string MinimumPeople {
            get {
                return ResourceManager.GetString("MinimumPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Minimum number of people cannot exceed the Total number of people..
        /// </summary>
        public static string MinimumPeopleText {
            get {
                return ResourceManager.GetString("MinimumPeopleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Questionnaire required.
        /// </summary>
        public static string Questionnaire {
            get {
                return ResourceManager.GetString("Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Questionnaires required.
        /// </summary>
        public static string Questionnaires {
            get {
                return ResourceManager.GetString("Questionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must choose at least 2 questionnaires..
        /// </summary>
        public static string QuestionnairesText {
            get {
                return ResourceManager.GetString("QuestionnairesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Questionnaire can not be null..
        /// </summary>
        public static string QuestionnaireText {
            get {
                return ResourceManager.GetString("QuestionnaireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start date can&apos;t be earlier than the current date..
        /// </summary>
        public static string StartDateTestText {
            get {
                return ResourceManager.GetString("StartDateTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The test you are trying to access has not yet begun..
        /// </summary>
        public static string StartDateText {
            get {
                return ResourceManager.GetString("StartDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weighing.
        /// </summary>
        public static string Weighing {
            get {
                return ResourceManager.GetString("Weighing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The categories weighing must be a decimal number whit the format: 99.999..
        /// </summary>
        public static string WeighingInvalid {
            get {
                return ResourceManager.GetString("WeighingInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weights required.
        /// </summary>
        public static string WeighingNull {
            get {
                return ResourceManager.GetString("WeighingNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The values ​​for weight categories cannot be null..
        /// </summary>
        public static string WeighingNullText {
            get {
                return ResourceManager.GetString("WeighingNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The sum of all percentages must equal 100..
        /// </summary>
        public static string WeighingText {
            get {
                return ResourceManager.GetString("WeighingText", resourceCulture);
            }
        }
    }
}
