//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Views.Question {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Create {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Create() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedinetClassLibrary.Resources.Views.Question.Create", typeof(Create).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dichotomous Answers.
        /// </summary>
        public static string DichotomousAnswers {
            get {
                return ResourceManager.GetString("DichotomousAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        public static string DropDownCategories {
            get {
                return ResourceManager.GetString("DropDownCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Questionnaire.
        /// </summary>
        public static string DropDownQuestionnaires {
            get {
                return ResourceManager.GetString("DropDownQuestionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type of question.
        /// </summary>
        public static string DropDownQuestionTypes {
            get {
                return ResourceManager.GetString("DropDownQuestionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mixed Answers.
        /// </summary>
        public static string MixedAnswers {
            get {
                return ResourceManager.GetString("MixedAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiple Selection Answers.
        /// </summary>
        public static string MultipleSelectionAnswers {
            get {
                return ResourceManager.GetString("MultipleSelectionAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Questions &gt; Create.
        /// </summary>
        public static string PathCreate {
            get {
                return ResourceManager.GetString("PathCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selection answers.
        /// </summary>
        public static string SelectionAnswers {
            get {
                return ResourceManager.GetString("SelectionAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text answers.
        /// </summary>
        public static string TextAnswers {
            get {
                return ResourceManager.GetString("TextAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create question.
        /// </summary>
        public static string TitleCreate {
            get {
                return ResourceManager.GetString("TitleCreate", resourceCulture);
            }
        }
    }
}
