//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Views.Test {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Create {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Create() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedinetClassLibrary.Resources.Views.Test.Create", typeof(Create).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add questionnaires.
        /// </summary>
        public static string AddQuestionnaires {
            get {
                return ResourceManager.GetString("AddQuestionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate sample.
        /// </summary>
        public static string CalculateSample {
            get {
                return ResourceManager.GetString("CalculateSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confidence level.
        /// </summary>
        public static string ConfidenceLevel {
            get {
                return ResourceManager.GetString("ConfidenceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demographic.
        /// </summary>
        public static string Demographic {
            get {
                return ResourceManager.GetString("Demographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demographics to test.
        /// </summary>
        public static string DemographicsInTest {
            get {
                return ResourceManager.GetString("DemographicsInTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate evaluation number.
        /// </summary>
        public static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matching.
        /// </summary>
        public static string Marching {
            get {
                return ResourceManager.GetString("Marching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matching.
        /// </summary>
        public static string Matching {
            get {
                return ResourceManager.GetString("Matching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the selector demographic and the questionnaires.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tests &gt; Create.
        /// </summary>
        public static string PathCreate {
            get {
                return ResourceManager.GetString("PathCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selector demographic.
        /// </summary>
        public static string SelectorDemographic {
            get {
                return ResourceManager.GetString("SelectorDemographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selector values.
        /// </summary>
        public static string SelectorValues {
            get {
                return ResourceManager.GetString("SelectorValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Standard error.
        /// </summary>
        public static string StandardError {
            get {
                return ResourceManager.GetString("StandardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create test.
        /// </summary>
        public static string TitleCreate {
            get {
                return ResourceManager.GetString("TitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of employees in your company.
        /// </summary>
        public static string TotalEmployees {
            get {
                return ResourceManager.GetString("TotalEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Number of employees field must be a whole number greater than zero..
        /// </summary>
        public static string ValidateInt {
            get {
                return ResourceManager.GetString("ValidateInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All fields are required.
        /// </summary>
        public static string ValidationTip {
            get {
                return ResourceManager.GetString("ValidationTip", resourceCulture);
            }
        }
    }
}
