//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Brochure {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Brochure() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedinetClassLibrary.Resources.Views.Home.Brochure", typeof(Brochure).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With its powerful statistical processing module, the data analysis is performed by the application and completely online, identifying the significant factors affecting your company’s climate..
        /// </summary>
        public static string AutomatedAnalysisText {
            get {
                return ResourceManager.GetString("AutomatedAnalysisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated analysis.
        /// </summary>
        public static string AutomatedAnalysisTitle {
            get {
                return ResourceManager.GetString("AutomatedAnalysisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You decide when to apply a test - It is easy and simple. Just select an option and the system prepares instantly an evaluation and sends it to the people you want to measure. Once the application form is completed, the information is stored in our servers and processed automatically..
        /// </summary>
        public static string AutomatedDataCollectionText {
            get {
                return ResourceManager.GetString("AutomatedDataCollectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated  data collection.
        /// </summary>
        public static string AutomatedDataCollectionTitle {
            get {
                return ResourceManager.GetString("AutomatedDataCollectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our measurements are handled in the strictest confidentiality.
        /// </summary>
        public static string FeaturesText1 {
            get {
                return ResourceManager.GetString("FeaturesText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no need to use paper, all surveys are electronic.
        /// </summary>
        public static string FeaturesText2 {
            get {
                return ResourceManager.GetString("FeaturesText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analysis is automated; you can review it at any time.
        /// </summary>
        public static string FeaturesText3 {
            get {
                return ResourceManager.GetString("FeaturesText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed statistics with easily-presented results.
        /// </summary>
        public static string FeaturesText4 {
            get {
                return ResourceManager.GetString("FeaturesText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to perform ranking in your company’s market sector.
        /// </summary>
        public static string FeaturesText5 {
            get {
                return ResourceManager.GetString("FeaturesText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global scope, you can analyze all your offices around the world..
        /// </summary>
        public static string FeaturesText6 {
            get {
                return ResourceManager.GetString("FeaturesText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string FeaturesTitle {
            get {
                return ResourceManager.GetString("FeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for a free service demo! Contact us!.
        /// </summary>
        public static string FreeDemo {
            get {
                return ResourceManager.GetString("FreeDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will allow you to have an overview of your organization. Through using streetlight analogy, you will be able to identify your company’s strengths and hotspots, to review each office, region or country analysis, and also to apply new measurement surveys when you need it..
        /// </summary>
        public static string GlobalScopeText {
            get {
                return ResourceManager.GetString("GlobalScopeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global scope.
        /// </summary>
        public static string GlobalScopeTitle {
            get {
                return ResourceManager.GetString("GlobalScopeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the tool of our system &amp;lt;strong&amp;gt;T360&amp;lt;/strong&amp;gt; &amp;lt;a target=&quot;_blank&quot; href=&quot;https://www.talentoen360.com&quot;&amp;gt;www.talentoen360.com&amp;lt;/a&amp;gt; that allows to proactively carry out massive evaluations using measurement instruments, with immediate processing and with global reach, speeding up decision-making, due to its robust statistical analysis capacity. No matter where you are, you can analyze data or apply evaluations with just one click, without costly travel and without using paper..
        /// </summary>
        public static string MainText {
            get {
                return ResourceManager.GetString("MainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achieve the best climate for your organization.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It offers a variety of reports that will allow you to make the best decisions. From data analysis on the study sample to executive reports, it even allows you to have a ranking where you can compare yourself with our measurement base..
        /// </summary>
        public static string VarietyOfRportsText {
            get {
                return ResourceManager.GetString("VarietyOfRportsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety of reports.
        /// </summary>
        public static string VarietyOfRportsTitle {
            get {
                return ResourceManager.GetString("VarietyOfRportsTitle", resourceCulture);
            }
        }
    }
}
