//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedinetClassLibrary.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Images/img-galeria/analisis.png.
        /// </summary>
        public static string AnalysisImage {
            get {
                return ResourceManager.GetString("AnalysisImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose company.
        /// </summary>
        public static string ChooseCompany {
            get {
                return ResourceManager.GetString("ChooseCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your code here:.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For best performance of the application we recommend using Internet Explorer 9, Firefox or Google Chrome. Very old versions (Internet Explorer less than version 8), may present some problems..
        /// </summary>
        public static string DisplayProblems {
            get {
                return ResourceManager.GetString("DisplayProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Images/img-galeria/estadisticas.png.
        /// </summary>
        public static string EstImage {
            get {
                return ResourceManager.GetString("EstImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedbacks.
        /// </summary>
        public static string Feedbacks {
            get {
                return ResourceManager.GetString("Feedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Images/img-galeria/flexibilidad.png.
        /// </summary>
        public static string FlexibilityImage {
            get {
                return ResourceManager.GetString("FlexibilityImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global result.
        /// </summary>
        public static string GlobalClimate {
            get {
                return ResourceManager.GetString("GlobalClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../Content/Images/icon-system/help.png.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpMsg {
            get {
                return ResourceManager.GetString("HelpMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About HRMedinet.
        /// </summary>
        public static string HRMedinetPath {
            get {
                return ResourceManager.GetString("HRMedinetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is an automated tool which allows to easy and quickly perform organizational climate assessments, supported by web technology and the best practices of the technological world..
        /// </summary>
        public static string HRMedinetText1 {
            get {
                return ResourceManager.GetString("HRMedinetText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has no restrictions when it comes to the number of users and the geographical location, and it can also be used on computer equipments and mobile devices for maximum flexibility..
        /// </summary>
        public static string HRMedinetText2 {
            get {
                return ResourceManager.GetString("HRMedinetText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resources Solutions.
        /// </summary>
        public static string ImageMsj1 {
            get {
                return ResourceManager.GetString("ImageMsj1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individuals measurements.
        /// </summary>
        public static string ImageMsj2 {
            get {
                return ResourceManager.GetString("ImageMsj2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic measurements and results.
        /// </summary>
        public static string ImageMsj3 {
            get {
                return ResourceManager.GetString("ImageMsj3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your teamwork.
        /// </summary>
        public static string ImageMsj4 {
            get {
                return ResourceManager.GetString("ImageMsj4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfaction surveys.
        /// </summary>
        public static string ImageMsj5 {
            get {
                return ResourceManager.GetString("ImageMsj5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance evaluations.
        /// </summary>
        public static string ImageMsj6 {
            get {
                return ResourceManager.GetString("ImageMsj6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        public static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer assessment solutions of Organizational Climate which allow to proactively detect problems using reliable instruments and a specialized statistic analysis that will help to promote the development of human capital in favor of your company’s professionals and organizational growth..
        /// </summary>
        public static string MedinetText {
            get {
                return ResourceManager.GetString("MedinetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRMedinet is a tool which proactively allows you to determine your company’s climate immediately and with global scope; speeding up decision-making due to its solid statistical analysis capacity..
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies that have used HrMedinet.
        /// </summary>
        public static string Ourclients {
            get {
                return ResourceManager.GetString("Ourclients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string PathIndex {
            get {
                return ResourceManager.GetString("PathIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../Content/Images/img-galeria/result.jpg.
        /// </summary>
        public static string ResultImage {
            get {
                return ResourceManager.GetString("ResultImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a company.
        /// </summary>
        public static string SelectCompany {
            get {
                return ResourceManager.GetString("SelectCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate.
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string TitleIndex {
            get {
                return ResourceManager.GetString("TitleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to HRMedinet.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is an automated tool that allows you to carry out massive evaluations easily and quickly, supported by web technology and the best practices of the technological world..
        /// </summary>
        public static string WelcomeText1 {
            get {
                return ResourceManager.GetString("WelcomeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has no geographical or number of user limitations, and can be used on both computer equipment and mobile devices for greater flexibility..
        /// </summary>
        public static string WelcomeText2 {
            get {
                return ResourceManager.GetString("WelcomeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRMedinet has a robust statistical analysis module that will allow you to obtain as much information as possible from your evaluation, avoiding additional consulting costs for interpretation of results and with the necessary recommendations to carry out the actions that your company really requires..
        /// </summary>
        public static string WelcomeText3 {
            get {
                return ResourceManager.GetString("WelcomeText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We support the conservation of our environment since all our reports are electronic, not a single sheet of paper is required during the entire measurement process..
        /// </summary>
        public static string WelcomeText4 {
            get {
                return ResourceManager.GetString("WelcomeText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new?.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
    }
}
