//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Services {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Services() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedinetClassLibrary.Resources.Views.Home.Services", typeof(Services).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to our services.
        /// </summary>
        public static string BackToServices {
            get {
                return ResourceManager.GetString("BackToServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        public static string Benefits {
            get {
                return ResourceManager.GetString("Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string COdescription {
            get {
                return ResourceManager.GetString("COdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures of Laboral Climate allows you to set strategies that optimize productive behavior in employees, helping the employees to work enthusiastically and effectively. The results that you could obtain trough this kind of assessment, allow you to understand the actions and reactions of employees in their work environment, as well as their responsibility, commitment, productivity and respect for the rules and policies of the company..
        /// </summary>
        public static string Dmsj1 {
            get {
                return ResourceManager.GetString("Dmsj1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently, Perez de Maldonado (2004) argues that the work environment or organizational environment can be understood as a &quot;socially constructed phenomenon, arising from individual-group interactions- laboral conditions, and results in a meaningfully experience both individual and as a group, because what belongs and occurs in the organization affects and interacts with everything in it. Laboral Climate are precisely the result of these interactions, that occur in a dynamic, changing and emotional way&quot;..
        /// </summary>
        public static string Dmsj2 {
            get {
                return ResourceManager.GetString("Dmsj2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 360º assessment is a technique that is increasingly used in modern companies.  Also known as integrated assessment, it aims to provide employees with an overview of its performance as reliable as possible, obtaining information from all possible points of view, including managers, colleagues, internal and external customers and subordinates..
        /// </summary>
        public static string E360msj1 {
            get {
                return ResourceManager.GetString("E360msj1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal of this integrated assessment is to provide the employee or the company full and objective feedback, necessary to take the actions in order to improve employee performance in his workplace..
        /// </summary>
        public static string E360msj2 {
            get {
                return ResourceManager.GetString("E360msj2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through its enforcement, we could obtain invaluable information for the Human Resources department, as it provides the guide to actions to be taken in short, medium and long term..
        /// </summary>
        public static string E360msj3 {
            get {
                return ResourceManager.GetString("E360msj3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It helps you to determine the performance of each of the evaluated according to the competencies, skills and behaviors that are important for the company..
        /// </summary>
        public static string E360msj4 {
            get {
                return ResourceManager.GetString("E360msj4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies individual skill levels in different areas..
        /// </summary>
        public static string E360msj5 {
            get {
                return ResourceManager.GetString("E360msj5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes it possible to undertake specific actions to improve and develop the employees’ performance..
        /// </summary>
        public static string E360msj6 {
            get {
                return ResourceManager.GetString("E360msj6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally, this evaluation benefits human development, producing a positive impact on the progress of the company, increasing the effective actions and working performance.  At the end of the day, you will get a significance increase in quality of products or services offered by the company..
        /// </summary>
        public static string E360msj7 {
            get {
                return ResourceManager.GetString("E360msj7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lately there has been a important increase in the competencies investigation, which has provided significant contributions to the business field, associated largely with the develop and optimization of Human Resources processes.  Competencies are individual underlying factors, which are related to a number of skills, behavioral tendencies, knowledge and attitudes that explains the effective and successful performance in work environment..
        /// </summary>
        public static string ENDmsj1 {
            get {
                return ResourceManager.GetString("ENDmsj1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its features are: &lt;br /&gt;
        ///1. They are permanent.&lt;br /&gt;
        ///2. They find its way out when the employees execute a task related with their job.&lt;br /&gt;
        ///3. They  actually caused the work performance, not only are related with it.&lt;br /&gt;
        ///4. They show themselves up in several activities.&lt;br /&gt;.
        /// </summary>
        public static string ENDmsj2 {
            get {
                return ResourceManager.GetString("ENDmsj2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The possibility to diagnose competencies in a company, implies the possibility to know which behaviors, attitudes and skills are required to be successful as a employee in it, providing the necessary information to create the different job profiles to the Human Resources department. Likewise it allows them to make the correct matches position-employee, according with the competencies related with each position..
        /// </summary>
        public static string ENDmsj3 {
            get {
                return ResourceManager.GetString("ENDmsj3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In addition, the correct competencies diagnose allows you to design developing plans to your employees, in order to increase their competencies level when they are very low or nonexistent..
        /// </summary>
        public static string ENDmsj4 {
            get {
                return ResourceManager.GetString("ENDmsj4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competencies Assessment (Assessment Centres).
        /// </summary>
        public static string ENDTitle {
            get {
                return ResourceManager.GetString("ENDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifically, applying a measurement of  Laboral Climate, allows companies to:.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboral Climate.
        /// </summary>
        public static string OrganizationalClimateTitle {
            get {
                return ResourceManager.GetString("OrganizationalClimateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational diagnostics.
        /// </summary>
        public static string Service1 {
            get {
                return ResourceManager.GetString("Service1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational climate and culture.
        /// </summary>
        public static string Service2 {
            get {
                return ResourceManager.GetString("Service2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mysterious client.
        /// </summary>
        public static string Service3 {
            get {
                return ResourceManager.GetString("Service3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys for market research.
        /// </summary>
        public static string Service4 {
            get {
                return ResourceManager.GetString("Service4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys tailored to customer requirements..
        /// </summary>
        public static string Service5 {
            get {
                return ResourceManager.GetString("Service5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify strengths and weaknesses in the work environment..
        /// </summary>
        public static string Subitem1 {
            get {
                return ResourceManager.GetString("Subitem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have qualitative and quantitative indicators of the main processes and human management variables..
        /// </summary>
        public static string Subitem2 {
            get {
                return ResourceManager.GetString("Subitem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiy critical points that require priority attention..
        /// </summary>
        public static string Subitem3 {
            get {
                return ResourceManager.GetString("Subitem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify the focus of the weaknesses that the organization can present.
        /// </summary>
        public static string Subitem4 {
            get {
                return ResourceManager.GetString("Subitem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establish improvement and action plans..
        /// </summary>
        public static string Subitem5 {
            get {
                return ResourceManager.GetString("Subitem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide a wide variety of specialized services in organizational and business consulting, based on the real needs of our clients. The results of the evaluations, measurements and investigations are generated on a Web page, guaranteeing the security, saving paper and confidentiality of the information collected..
        /// </summary>
        public static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, we offer the following services:.
        /// </summary>
        public static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement of Laboral Climate..
        /// </summary>
        public static string Text3 {
            get {
                return ResourceManager.GetString("Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement of Competencies Assessment (Assessment Centres)..
        /// </summary>
        public static string Text4 {
            get {
                return ResourceManager.GetString("Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance 360°..
        /// </summary>
        public static string Text5 {
            get {
                return ResourceManager.GetString("Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design of an intervention plan..
        /// </summary>
        public static string Text6 {
            get {
                return ResourceManager.GetString("Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation of workshops and conferences..
        /// </summary>
        public static string Text7 {
            get {
                return ResourceManager.GetString("Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designs and implementations of surveys..
        /// </summary>
        public static string Text8 {
            get {
                return ResourceManager.GetString("Text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing, instruments, automation and measurements..
        /// </summary>
        public static string Text9 {
            get {
                return ResourceManager.GetString("Text9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
